kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pod
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/jenkins"
